version: '3.8'

services:
  web: &django_gunicorn
    build:
      context: . 
      dockerfile: Dockerfile.prod
#    command: gunicorn multichat.wsgi:application --bind 0.0.0.0:8000
    command: daphne -p 8000 multichat.asgi:application -b 0.0.0.0
    expose:
      - 8000
      - 8001
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
  redis:
    image: redis
    ports:
      - "6379:6379"
  
volumes:
  postgres_data:
  static_volume: